[package]
name = "metrics-controller"
version = "0.1.0"
authors = ["thills <thills@mozilla.com", "russn <russn@mozilla.com"]


[dependencies]
serde = "0.6.11"
serde_json = "0.6.0"
serde_macros = "0.6.11"
flate2 = "0.2.13"
hyper = "~0.7"
uuid = "0.1.18"
time = "0.1"
